name: Create luci-app-NPc 

on:
  workflow_dispatch:    # 支持手动触发
  # schedule:
  #  - cron: '0 0 * * *' # 每天 UTC 0 点自动执行

jobs:
  create-repo-and-sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1：安装 GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/gith[...]
          sudo apt-get update
          sudo apt-get install -y gh

      # 步骤 2：创建新仓库
      - name: Create New Repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # 检查仓库是否已存在
          if gh repo view a1303045940/luci-app-npc >/dev/null 2>&1; then
            echo "ℹ️ 仓库已存在，跳过创建"
          else
            echo "=== 创建新仓库 ==="
            gh repo create a1303045940/luci-app-npc --public --confirm
            echo "✅ 新仓库已创建：https://github.com/a1303045940/luci-app-npc"
          fi

      # 步骤 3：检出新创建的仓库
      - name: Checkout New Repository
        uses: actions/checkout@v4
        with:
          repository: a1303045940/luci-app-npc
          token: ${{ secrets.GH_TOKEN }}
          path: new-repo
          fetch-depth: 1  # 仅获取最新提交

      # 步骤 4：获取源目录内容
      - name: Fetch Source Directory
        run: |
          mkdir -p source-files
          cd source-files
          git init
          git remote add origin https://github.com/kiddin9/kwrt-packages.git
          git config core.sparseCheckout true
          echo "package/kwrt-packages/*" >> .git/info/sparse-checkout  # 获取目录下所有内容
          git pull --depth=1 origin master
          
          # 验证源目录
          if [ ! -d "package/kwrt-packages" ]; then
            echo "❌ 错误：源目录 package/kwrt-packages 不存在"
            exit 1
          fi

      # 步骤 5：复制文件到新仓库（仅目录内容）
      - name: Copy Files to New Repository
        run: |
          SOURCE_DIR="source-files/package/kwrt-packages"
          TARGET_DIR="new-repo"
          
          echo "=== 清空目标仓库 ==="
          find "$TARGET_DIR" -mindepth 1 -delete  # 删除所有内容但保留.git目录
          
          echo "=== 复制文件（不包括父目录）==="
          # 复制package/kwrt-packages目录下的所有内容到仓库根目录
          rsync -av --progress "$SOURCE_DIR/" "$TARGET_DIR/" 
          
          echo "=== 文件复制完成 ==="
          echo "访问链接：https://github.com/a1303045940/luci-app-npc"
          ls -la "$TARGET_DIR"

      # 步骤 6：提交并推送到新仓库
      - name: Commit & Push to New Repository
        run: |
          cd new-repo
          git config user.name "GitHub Actions"
          git config user.email "1303045940@qq.com"
          
          # 添加所有变更
          git add .
          
          # 检测变更并提交
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "feat: Initial commit from package/kwrt-packages source"
            git push
            echo "✅ 文件已推送到新仓库：https://github.com/a1303045940/luci-app-npc"
          else
            echo "ℹ️ 无文件变更，跳过提交"
          fi
