name: Sync NPC Directory

on:
  workflow_dispatch:    # 支持手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0 点自动执行

jobs:
  sync-npc:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1：检出目标仓库 (CloseWRT-CI-rb30b1-24.1)
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: a1303045940/CloseWRT-CI-rb30b1-24.1
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo

      # 步骤 2：获取源目录内容 (luci-app-npc)
      - name: Fetch Source Directory
        run: |
          mkdir source-files
          cd source-files
          git init
          git remote add origin https://github.com/sqshanbing/small-package.git
          git config core.sparseCheckout true
          echo "luci-app-npc/*" >> .git/info/sparse-checkout
          git pull origin 3cbc43ba94a0f414d34273a207e0c41a2d1d391b

      # 步骤 3：复制文件到目标仓库
      - name: Copy Files to Target
        run: |
          # 清空目标目录（可选）
          rm -rf target-repo/luci-app-npc
          
          # 复制文件并保留路径结构
          mkdir -p target-repo/luci-app-npc
          cp -r source-files/luci-app-npc/* target-repo/luci-app-npc/
          
          # 验证文件结构
          ls -lR target-repo/luci-app-npc

      # 步骤 4：提交并推送更改
      - name: Commit & Push Changes
        run: |
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 检测变更并提交
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: Update luci-app-npc from source"
            git push
          else
            echo "No changes detected"
          fi
