name: Sync luci-app-npc to My Repo

on:
  workflow_dispatch:    # 支持手动触发
  # schedule:
  #   - cron: '0 0 * * *' # 每天 UTC 0 点自动执行

jobs:
  sync-luci-app-npc:
    runs-on: ubuntu-latest
    steps:
      # 安装 GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh

      # 检查并创建新仓库
      - name: Create New Repository if Not Exists
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if gh repo view a1303045940/luci-app-npc >/dev/null 2>&1; then
            echo "ℹ️ 仓库已存在，跳过创建"
          else
            echo "=== 创建新仓库 ==="
            gh repo create a1303045940/luci-app-npc --public --confirm
            echo "✅ 新仓库已创建：https://github.com/a1303045940/luci-app-npc"
          fi

      # 检出新仓库
      - name: Checkout New Repository
        uses: actions/checkout@v4
        with:
          repository: a1303045940/luci-app-npc
          token: ${{ secrets.GH_TOKEN }}
          path: new-repo
          fetch-depth: 1

      # 仅拉取 luci-app-npc 目录（稀疏检出）
      - name: Sparse Checkout luci-app-npc
        run: |
          git clone --depth=1 --filter=blob:none --sparse https://github.com/kiddin9/kwrt-packages.git package/kwrt-packages
          cd package/kwrt-packages
          git sparse-checkout set luci-app-npc
          cd ../

      # 拷贝 luci-app-npc 到新仓库
      - name: Copy luci-app-npc files to new repository
        run: |
          SOURCE_DIR="package/kwrt-packages/luci-app-npc"
          TARGET_DIR="new-repo"
          find "$TARGET_DIR" -mindepth 1 -delete
          if [ ! -d "$SOURCE_DIR" ]; then
            echo "❌ 目录 $SOURCE_DIR 不存在"
            exit 1
          fi
          rsync -av --progress "$SOURCE_DIR/" "$TARGET_DIR/"
          echo "=== 文件复制完成 ==="
          ls -la "$TARGET_DIR"

      # 提交并推送到新仓库
      - name: Commit & Push to New Repository
        run: |
          if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
          git init
          git remote add origin https://github.com/a1303045940/CloseWRT-CI-rb30b1-24.1.git
          git fetch
          git checkout main  # 如果你的主分支不是 main，请改成你的分支名
          fi
          cd new-repo
          git config user.name "GitHub Actions"
          git config user.email "1303045940@qq.com"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "feat: Initial sync from kiddin9/kwrt-packages/luci-app-npc"
            git push
            echo "✅ 文件已推送到新仓库：https://github.com/a1303045940/luci-app-npc"
          else
            echo "ℹ️ 无文件变更，跳过提交"
