name: Sync luci-app-npc to Target Repo

on:
  workflow_dispatch:    # 支持手动触发
  #schedule:
  #  - cron: '0 0 * * *' # 每天 UTC 0 点自动执行

jobs:
  sync-npc:
    runs-on: ubuntu-latest
    env:
      TARGET_REPO: "a1303045940/package"
      TARGET_DIR: "luci-app-npc"  # 对应的目标目录路径
      COMMIT_HASH: "3cbc43ba94a0f414d34273a207e0c41a2d1d391b"  # 源仓库特定提交
    
    steps:
      # 步骤 1：检出目标仓库
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ secrets.GH_TOKEN }}
          path: target-repo
          ref: main  # 明确指定目标分支

      # 步骤 2：获取源目录内容
      - name: Fetch Source Directory
        run: |
          mkdir -p source-files
          cd source-files
          git init
          git remote add origin https://github.com/sqshanbing/small-package.git
          git config core.sparseCheckout true
          echo "${{ env.TARGET_DIR }}/" >> .git/info/sparse-checkout
          git pull --depth=1 origin ${{ env.COMMIT_HASH }}
          
          # 验证源目录存在性
          if [ ! -d "${{ env.TARGET_DIR }}" ]; then
            echo "❌ 错误：源目录 ${{ env.TARGET_DIR }} 不存在"
            exit 1
          fi

      # 步骤 3：精确复制文件到目标目录
      - name: Copy Files to Target
        run: |
          SOURCE="source-files/${{ env.TARGET_DIR }}"
          TARGET="target-repo/${{ env.TARGET_DIR }}"
          
          echo "=== 清理目标目录 ==="
          rm -rf "$TARGET"  # 完全删除旧目录
          
          echo "=== 复制文件到目标仓库 ==="
          mkdir -p "$TARGET"
          rsync -av --progress "$SOURCE/" "$TARGET/"
          
          echo "✅ 文件已复制到：https://github.com/${{ env.TARGET_REPO }}/tree/main/${{ env.TARGET_DIR }}"
          echo "=== 目录结构验证 ==="
          tree "$TARGET" || ls -lR "$TARGET"

      # 步骤 4：提交并推送更改
      - name: Commit & Push Changes
        run: |
          cd target-repo
          git config user.name "GitHub Actions"
          git config user.email "1303045940@qq.com"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add "${{ env.TARGET_DIR }}"
            git commit -m "chore: Update ${{ env.TARGET_DIR }} from source $(date +'%Y%m%d-%H%M%S')"
            git push
            echo "✅ 更新已推送到：https://github.com/${{ env.TARGET_REPO }}/tree/main/${{ env.TARGET_DIR }}"
          else
            echo "ℹ️ 无文件变更，跳过提交"
          fi
